#!/bin/bash

# CLAUDE.md 自動生成スクリプト
# .cursor/rules/core/ ディレクトリの内容を自動的に CLAUDE.md にマージ

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CORE_DIR="$SCRIPT_DIR/core"
OUTPUT_FILE="$PROJECT_ROOT/CLAUDE.md"

# ヘッダーを生成
cat > "$OUTPUT_FILE" << 'EOF'
# CLAUDE.md

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

**Note**: This file is automatically generated from `.cursor/rules/core/*.mdc` files.
To modify the content, edit the source files in `.cursor/rules/core/` and run `.cursor/rules/sync-to-claude.sh`.

---

EOF

# core/ ディレクトリ内のファイルを順番にマージ
for file in "$CORE_DIR"/commands.mdc "$CORE_DIR"/architecture.mdc "$CORE_DIR"/critical-rules.mdc "$CORE_DIR"/spec-workflow.mdc; do
  if [ -f "$file" ]; then
    echo "" >> "$OUTPUT_FILE"
    # ファイル内容を追加（最初の行（# タイトル）を除く）
    tail -n +2 "$file" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
  fi
done

echo "✅ CLAUDE.md has been generated successfully from .cursor/rules/core/ files."
echo "📝 Output: $OUTPUT_FILE"
